#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

from sys import exit
from wellpapp import Client
from argparse import ArgumentParser

def short(tag):
	print tag.name

def long(tag):
	names = [tag.name] + sorted(tag.alias)
	props = [str(p) for p in tag.type, tag.posts, tag.weak_posts]
	if tag.valuetype: props.insert(0, "valuetype:" + tag.valuetype)
	print " ".join(names + props)

def tagsort(a, b):
	return cmp(a.name, b.name)

parser = ArgumentParser()
parser.add_argument("-f", "--fuzzy", action="store_true", help="Fuzzy matching")
parser.add_argument("-a", "--anywhere", action="store_true", help="Match anywhere")
parser.add_argument("-s", "--short", action="store_true", help="Short listing (just tagnames)")
parser.add_argument(metavar="partial-tag-name", dest="part")
args = parser.parse_args()

client = Client()
match = "F" if args.fuzzy else "E"
where = "P" if args.anywhere else "I"
cmd = match + "A" + where
printer = short if args.short else long
map(printer, sorted(client.find_tags(cmd, args.part), tagsort))
