#!/usr/bin/env python3

from __future__ import print_function

from sys import argv, exit
from wellpapp import Client

if len(argv) not in (3, 4, 5):
	print("Usage:", argv[0], "tag new_name [new_type [new_valuetype]]")
	exit(1)

a = {}
if len(argv) > 3:
	a["type"] = argv[3]
if len(argv) > 4:
	a["valuetype"] = argv[4]

client = Client()
tag = client.find_tag(argv[1])
a["name"] = argv[2]
if not tag:
	print("Tag not found")
	exit(1)
client.mod_tag(tag, **a)
