#!/usr/bin/env python3

from __future__ import print_function

from sys import argv, exit
from wellpapp import Client

if len(argv) < 3:
	print("Usage:", argv[0], "tagname post-spec [post-spec [...]]")
	exit(1)

client = Client()
data = {}
tag = client.find_tag(argv[1], data)
if not tag:
	print("Tag not found")
	exit(1)
if data["weak_posts"]:
	print("Can't order a tag with weak posts")
	exit(1)
posts = map(client.postspec2md5, argv[2:])
wtag = "~" + tag
for post, spec in zip(posts, argv[2:]):
	if post:
		post = client.get_post(post, True)
	if not post:
		print("Post " + spec + " not found")
		exit(1)
	if tag in post.implfulltags or tag in post.implweaktags:
		print("Post " + spec + " has tag implied.")
		print("Can't order a tag with implied posts.")
		exit(1)
	if tag not in post.tags.guids:
		print("Post " + spec + " doesn't have tag.")
		exit(1)
client.order(tag, posts)
