#!/usr/bin/env python3

from __future__ import print_function

from sys import argv, exit
from wellpapp import Client

if len(argv) != 2:
	print("Usage:", argv[0], "alias")
	exit(1)

client = Client()
client.remove_alias(argv[1])
