#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

from sys import argv, exit
from wellpapp import Client

if len(argv) != 3:
	print "Usage:", argv[0], "post-spec rotation"
	exit(1)

spec, new_r = argv[1:]
client = Client()
md5 = client.postspec2md5(spec)
post = None
if md5:
	post = client.get_post(md5, wanted = ["rotate", "ext", "width", "height"])
if not post:
	print "Post not found"
	exit(1)

r = int(post.get("rotate", 0))
new_r = int(new_r)
if r not in (0, 90, 180, 270) or abs(new_r) not in (90, 180, 270):
	print "Can only handle 90, 180 or 270 degrees rotation"
	exit(1)
dest_r = (r + new_r) % 360
props = {"rotate": dest_r}
if abs(new_r) in (90, 270):
	props["width"], props["height"] = post["height"], post["width"]

client.save_thumbs(md5, None, post.ext, dest_r, True)
client.modify_post(md5, **props)
